import React, { useState } from 'react';
import { GOALS, LEVELS, generateWeeklyPlan } from '../../services/workoutPlan/planMatrix';
import { dbService } from '../../services/api/dbService';
import { CheckCircle2, Sparkles, ArrowRight } from 'lucide-react';

export function OnboardingModal({ user, currentProfile, onComplete }) {
  const [step, setStep] = useState(1);
  const userName = currentProfile?.name || currentProfile?.username || user?.displayName || 'Атлет';
  const [goal, setGoal] = useState('muscle');
  const [level, setLevel] = useState('intermediate');
  const [frequency, setFrequency] = useState(3);
  const [isSaving, setIsSaving] = useState(false);

  const handleFinish = async () => {
    setIsSaving(true);
    // Request plan generated by FastAPI backend, or fallback to client matrix
    const backendPlan = await dbService.generatePlan(goal, level, frequency);
    const weeklyPlan = backendPlan || generateWeeklyPlan(goal, level, frequency);

    const profileData = {
      name: userName,
      goal,
      level,
      frequency,
    };

    await dbService.saveUserPlan(profileData, weeklyPlan);

    setIsSaving(false);
    onComplete({ ...currentProfile, ...profileData, activePlan: weeklyPlan, isOnboarded: true });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="w-full max-w-2xl glass-panel rounded-3xl p-6 sm:p-8 border border-blue-500/30 shadow-2xl glow-blue text-left">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/30 text-blue-400 text-xs font-semibold mb-3">
            <Sparkles className="w-3.5 h-3.5" /> Персонализация AI Плана
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-white">
            Создадим ваш индивидуальный план
          </h2>
          <p className="text-gray-400 text-sm mt-1">
            Шаг {step} из 3: {step === 1 ? 'Ваша цель' : step === 2 ? 'Уровень подготовки' : 'График тренировок'}
          </p>
        </div>

        {/* Step 1: Goal Selection */}
        {step === 1 && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 gap-3">
              {Object.entries(GOALS).map(([key, item]) => (
                <div
                  key={key}
                  onClick={() => setGoal(key)}
                  className={`p-4 rounded-2xl cursor-pointer transition-all border ${
                    goal === key
                      ? 'bg-blue-600/20 border-blue-500 shadow-lg glow-blue'
                      : 'bg-gray-800/40 border-gray-700/60 hover:bg-gray-800/80'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <span className="text-3xl">{item.icon}</span>
                      <div>
                        <h3 className="font-bold text-white text-base">{item.label}</h3>
                        <p className="text-xs text-gray-400 mt-0.5">{item.description}</p>
                      </div>
                    </div>
                    {goal === key && <CheckCircle2 className="w-5 h-5 text-blue-400 shrink-0" />}
                  </div>
                </div>
              ))}
            </div>

            <button
              onClick={() => setStep(2)}
              className="w-full py-3.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold transition-all flex items-center justify-center gap-2 shadow-lg glow-blue"
            >
              Далее <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        )}

        {/* Step 2: Fitness Level */}
        {step === 2 && (
          <div className="space-y-6">
            <div className="space-y-3">
              {Object.entries(LEVELS).map(([key, item]) => (
                <div
                  key={key}
                  onClick={() => setLevel(key)}
                  className={`p-4 rounded-2xl cursor-pointer transition-all border flex items-center justify-between ${
                    level === key
                      ? 'bg-blue-600/20 border-blue-500 shadow-lg'
                      : 'bg-gray-800/40 border-gray-700/60 hover:bg-gray-800/80'
                  }`}
                >
                  <div>
                    <h3 className="font-bold text-white text-base">{item.label}</h3>
                    <p className="text-xs text-gray-400 mt-1">
                      {item.sets} подхода • Пауза отдыха: {item.rest}с
                    </p>
                  </div>
                  {level === key && <CheckCircle2 className="w-5 h-5 text-blue-400" />}
                </div>
              ))}
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => setStep(1)}
                className="w-1/3 py-3 rounded-xl bg-gray-800 hover:bg-gray-700 text-gray-300 font-semibold transition-all"
              >
                Назад
              </button>
              <button
                onClick={() => setStep(3)}
                className="w-2/3 py-3 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold transition-all flex items-center justify-center gap-2 shadow-lg glow-blue"
              >
                Далее <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        )}

        {/* Step 3: Frequency & Schedule */}
        {step === 3 && (
          <div className="space-y-6">
            <div className="p-4 rounded-2xl bg-blue-500/10 border border-blue-500/30 flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-blue-600/30 border border-blue-500/40 flex items-center justify-center text-xl shrink-0">
                👋
              </div>
              <div>
                <div className="text-xs text-blue-300 font-bold uppercase tracking-wider">
                  Атлет: {userName}
                </div>
                <div className="text-xs text-gray-400 mt-0.5">
                  План тренировок формируется персонально для вас
                </div>
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-300 mb-2 uppercase">
                Частота тренировок в неделю
              </label>
              <div className="grid grid-cols-4 gap-3">
                {[2, 3, 4, 5].map((num) => (
                  <button
                    key={num}
                    onClick={() => setFrequency(num)}
                    className={`py-3.5 rounded-xl font-bold transition-all border ${
                      frequency === num
                        ? 'bg-blue-600 text-white border-blue-400 shadow-md glow-blue'
                        : 'bg-gray-800/50 text-gray-400 border-gray-700 hover:bg-gray-800'
                    }`}
                  >
                    {num} дня
                  </button>
                ))}
              </div>
            </div>

            <div className="flex gap-3 pt-2">
              <button
                onClick={() => setStep(2)}
                className="w-1/3 py-3.5 rounded-xl bg-gray-800 hover:bg-gray-700 text-gray-300 font-semibold transition-all"
              >
                Назад
              </button>
              <button
                onClick={handleFinish}
                disabled={isSaving}
                className="w-2/3 py-3.5 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-bold transition-all flex items-center justify-center gap-2 shadow-xl glow-blue"
              >
                <Sparkles className="w-5 h-5 text-yellow-300" /> {isSaving ? 'Сохранение...' : 'Сформировать & Сохранить'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
